# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "typescript-^3.1.1" = nodeEnv.buildNodePackage {
    name = "typescript";
    packageName = "typescript";
    version = "3.1.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript/-/typescript-3.1.6.tgz";
      sha512 = "tDMYfVtvpb96msS1lDX9MEdHrW4yOuZ4Kdc4Him9oU796XldPYF/t2+uKoX0BBa0hXXwDlqYQbXY5Rzjzc5hBA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript is a language for application scale JavaScript development";
      homepage = http://typescriptlang.org/;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}